### PR TITLE
Adding run forever

### PR DESCRIPTION
**Pull request by Jwdev-wr**
Still testing this let me know if you see anything outrageous about this solution

### CODE REVIEW

**Comment by slazarov** [comment]
I agree with https://github.com/slazarov/python-bittrex-websocket-aio/pull/5/commits/56187ee734ad7b2b3fbc11e8e3c39e5ee8fa1cee

Explain the `run_forever` parameter. I assume that when `run_forever = True` you want the client to exit if the connection is disconnected and vice versa. If that is true, then you haven't implemented it correctly because `e.code == 1000` is raised upon successful socket close, i.e it was triggered by the user through the method `def disconnect(self)`, hence no need for `run_forever` in the case of `e.code == 1000`

**Comment by Jwdev-wr** [comment]
@slazarov Ah I see, well as it is now the error code 1000 seems to be popping up randomly with no ws.disconnect() used. I thought this may have been coming from the bittrex websocket itself closing the connection after inactivity?

So I am trying to force the connection to reconnect upon that event.

> 2018-04-27 11:07:17 - bittrex_websocket.websocket_client - ERROR - WebSocket connection is closed: code = 1000 (OK), no reason. Initiating reconnection procedure <

That is what is happening.

Last night the run_forever did get it to reconnect although with some errors:

> 2018-04-27 11:07:18 - bittrex_websocket.websocket_client - ERROR - There was an error invoking Hub method 'c2.GetAuthContext'.<

Which I will look into today, unless you understand the root cause of this better than I do.

**Comment by slazarov** [comment]
Bittrex shutdown their endpoints yesterday temporary so this might have caused it. How often does it disconnect?

If you are developing actively I suggest joining the bittrex api-developers channel.

**Comment by Jwdev-wr** [comment]
I've been running it a couple days now, and it will disconnect at least once in every 8 hours or sooner. Yes I develop full-time I will have to find that bittrex api developer channel.

I'll keep observing and see what happens.

**Pull request closed without merging**
